<a href="https://colab.research.google.com/github/evilzeda/web-scrapping-project/blob/master/Twitter_Data_Scrapper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/JustAnotherArchivist/snscrape.git
  Cloning https://github.com/JustAnotherArchivist/snscrape.git to /tmp/pip-req-build-zac_bzon
  Running command git clone --filter=blob:none --quiet https://github.com/JustAnotherArchivist/snscrape.git /tmp/pip-req-build-zac_bzon
  Resolved https://github.com/JustAnotherArchivist/snscrape.git to commit 0d824ab77334ed4ab6250e5e491171afeccfb298
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from snscrape==0.6.2.20230321.dev50+g0d824ab) (2.27.1)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from snscrape==0.6.2.20230321.dev50+g0d824ab) (4.9.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from snscrape==0.6.2.20230321.dev50+g0d824ab) (4.11.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from snscrape==0.6.2.20230321.dev50+g0d824ab) (3.12.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->snscrape==0.6.2.20230321.dev50+g0d824ab) (2.4.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->snscrape==0.6.2.20230321.dev50+g0d824ab) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->snscrape==0.6.2.20230321.dev50+g0d824ab) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->snscrape==0.6.2.20230321.dev50+g0d824ab) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->snscrape==0.6.2.20230321.dev50+g0d824ab) (3.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->snscrape==0.6.2.20230321.dev50+g0d824ab) (1.7.1)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [20]:
import os
import datetime

# Limit the number of results taken
max_results = 10000

# Use Twitter search to find tweets that are favorites at least 10000 times and in Indonesian
twitter_search = "mamikos until:2023-06-14 since:2023-01-01"

# Specify a file name with the format "<search query>__<current date>.json"
filename = f"{twitter_search.replace(' ', '_').replace(':', '-').replace('#', '')}_{datetime.date.today().strftime('%Y-%m-%d')}.json"

USING_TOP_SEARCH = False

snscrape_params = '--jsonl --max-results'
twitter_search_params = ''

if USING_TOP_SEARCH:
    twitter_search_params += "--top"

snscrape_search_query = f"snscrape {snscrape_params} {max_results} twitter-search {twitter_search_params} '{twitter_search}' > {filename}"

print(snscrape_search_query)

os.system(snscrape_search_query)

snscrape --jsonl --max-results 10000 twitter-search  'mamikos until:2023-06-14 since:2023-01-01' > mamikos_until-2023-06-14_since-2023-01-01_2023-06-16.json

0

In [21]:
import pandas as pd
import ast
import json

# Read the result JSON file from the previous CLI command and create a pandas dataframe
tweets_df = pd.read_json(filename, lines=True)

CSV_FILE_NAME = 'mamikos.csv'

# Create a dictionary to rename columns
new_columns = {
    'conversationId': 'Conv. ID',
    'url': 'URL',
    'date': 'Date',
    'rawContent': 'Tweet',
    'id': 'ID',
    'replyCount': 'Replies',
    'retweetCount': 'Retweets',
    'likeCount': 'Likes',
    'quoteCount': 'Quotes',
    'bookmarkCount': 'Bookmarks',
    'lang': 'Language',
    'links': 'Links',
    'media': 'Media',
    'retweetedTweet': 'Retweeted Tweet',
    'username': 'Username'
}

if len(tweets_df) == 0:
    print('Pencarian tidak ditemukan coba ganti keyword lain, keywordmu: ', twitter_search)
    exit()
else:
  # Select the column to use and rename the column using the dictionary that has been created
  tweets_df = tweets_df.loc[:, ['url', 'date', 'rawContent', 'id',
                            'replyCount', 'retweetCount', 'likeCount', 'quoteCount',
                            'conversationId', 'lang', 'links',
                            'media', 'retweetedTweet', 'bookmarkCount', 'username']]
  tweets_df = tweets_df.rename(columns=new_columns)

  # Extract fullUrl from media field and url from links field
  tweets_df['Media'] = tweets_df['Media'].apply(lambda x: x[0]['fullUrl'] if isinstance(x, list) and x and isinstance(x[0], dict) and 'fullUrl' in x[0] else None)
  tweets_df['Links'] = tweets_df['Links'].apply(lambda x: x[0]['url'] if isinstance(x, list) and x and isinstance(x[0], dict) and 'url' in x[0] else None)

  # Display dataframe tweets_df
  display(tweets_df)

  # Save to csv
  # tweets_df.to_csv(CSV_FILE_NAME, index=False)

,URL,Date,Tweet,ID,Replies,Retweets,Likes,Quotes,Conv. ID,Language,Links,Media,Retweeted Tweet,Bookmarks,Username
0,https://twitter.com/ayangvei/status/1668658521...,2023-06-13 16:36:08+00:00,@ifrhit Mamikos harganya terlalu overpriced gt,1668658521888665600,1,0,0,0,1668487625798479872,in,None,None,NaN,0,ayangvei
1,https://twitter.com/ballsinyourarea/status/166...,2023-06-13 16:22:00+00:00,udah nyiapin tas gede sihh sama planning baju ...,1668654965483782144,0,0,1,0,1668654965483782144,in,None,None,NaN,0,ballsinyourarea
2,https://twitter.com/ConcacafID/status/16686367...,2023-06-13 15:09:42+00:00,@idextratime Orangnya lagi repot ngurusin buat...,1668636771146690561,0,1,22,0,1668635264464592898,in,None,None,NaN,0,ConcacafID
3,https://twitter.com/haanzhing888/status/166863...,2023-06-13 15:06:18+00:00,@dioxazinee_ uda coba cari-cari lewat aplikasi...,1668635916016193537,0,0,0,0,1668634214592561152,in,None,None,NaN,0,haanzhing888
4,https://twitter.com/Yourlovelygf_/status/16685...,2023-06-13 11:56:19+00:00,@jogmfs Klo pgn gampang bisa cari pake apk mam...,1668588103429410818,0,0,0,0,1668536688384299009,in,None,None,NaN,0,Yourlovelygf_
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1533,https://twitter.com/qiqiqi26/status/1609563489...,2023-01-01 14:53:34+00:00,@areabelajarr survey kos tu kita cari tau loka...,1609563489877757952,1,0,1,0,1609526020998303745,in,None,None,NaN,0,qiqiqi26
1534,https://twitter.com/_staywithskz/status/160953...,2023-01-01 12:57:36+00:00,Kosan di Bandung dari app mamikos ini kok jele...,1609534303951818752,1,0,0,0,1609534303951818752,in,None,None,NaN,0,_staywithskz
1535,https://twitter.com/areabelajarr/status/160952...,2023-01-01 12:26:28+00:00,1. Kos\n\nPinter-pinter survei kos dan tanya k...,1609526470803877888,9,19,573,12,1609526020998303745,in,None,None,NaN,44,areabelajarr
1536,https://twitter.com/reaboisasi/status/16094689...,2023-01-01 08:37:46+00:00,Kosan di mamikos kenapa mahal2 banget etdah,1609468914765033474,0,0,0,0,1609468914765033474,in,None,None,NaN,0,reaboisasi
1537,https://twitter.com/nonolaaaa/status/160938991...,2023-01-01 03:23:52+00:00,"@BoyzFess_ Coba cek mamikos nder, aku nemu dis...",1609389919981686785,0,0,0,0,1609387770233098241,in,None,None,NaN,0,nonolaaaa

In [ ]:
# Cek jumlah data yang didapatkan

num_tweets = len(tweets_df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 1.